version: "3.7"

services:
  database:
    image: postgres:14.2
    restart: always
    expose:
      - "5440"
    ports:
      - "5440:5440"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - from-the-morning-pgsql:/var/lib/postgresql/data
    networks:
      - skynet
    command: -p 5440
volumes:
  from-the-morning-pgsql:
    driver: local
networks:
  skynet:
    name: from-the-morning
